name: Test Document Build

on:
  pull_request:
  branches:
    - main
  paths:
    - docs/**

defaults:
  run:
    working-directory: docs

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
